const express = require('express')
const router = express.Router()
const geminiService = require('../services/geminiService')
const profileRepository = require('../db/profileRepository')
const programRepository = require('../db/programRepository')
const calorieService = require('../services/calorieService')
const validate = require('../middleware/validate')

/**
 * @swagger
 * tags:
 *   name: AI Suggestions
 *   description: Gemini AI powered workout and nutrition suggestions
 */

/**
 * @swagger
 * /api/ai/workout-suggestion:
 *   post:
 *     summary: Get personalized HIT workout plan from AI
 *     tags: [AI Suggestions]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [days_per_week, goal, experience_level, equipment]
 *             properties:
 *               days_per_week:
 *                 type: integer
 *                 minimum: 1
 *                 maximum: 7
 *                 example: 3
 *               available_days:
 *                 type: array
 *                 items:
 *                   type: integer
 *                 example: [1, 3, 5]
 *                 description: "1=Monday, 2=Tuesday, ..., 7=Sunday"
 *               goal:
 *                 type: string
 *                 enum: [muscle_gain, fat_loss, weight_loss, strength, endurance]
 *               experience_level:
 *                 type: string
 *                 enum: [beginner, intermediate, advanced]
 *               equipment:
 *                 type: string
 *                 enum: [gym, home, both]
 *               injuries:
 *                 type: string
 *                 example: "Lower back pain, avoid heavy deadlifts"
 *     responses:
 *       200:
 *         description: Personalized AI workout plan
 *       400:
 *         description: Validation error
 *       404:
 *         description: Profile not found
 *       503:
 *         description: AI service unavailable
 */
router.post('/workout-suggestion', validate.aiPreferences, async (req, res) => {
  try {
    const profile = await profileRepository.findByUserId(req.user.userId)
    if (!profile) {
      return res.status(404).json({
        error: 'Profile not found. Please create your profile first at POST /api/calories/profile'
      })
    }

    const age = calorieService.calculateAge(profile.birth_date)
    const profileWithAge = { ...profile, age }

    const suggestion = await geminiService.generateWorkoutSuggestion(
      profileWithAge,
      req.body
    )

    res.json(suggestion)
  } catch (err) {
    res.status(503).json({ error: err.message })
  }
})

/**
 * @swagger
 * /api/ai/workout-suggestion/save:
 *   post:
 *     summary: Save AI suggestion as a workout program
 *     tags: [AI Suggestions]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [name, days_per_week, goal]
 *             properties:
 *               name:
 *                 type: string
 *                 example: "AI Generated HIT Program"
 *               days_per_week:
 *                 type: integer
 *               goal:
 *                 type: string
 *                 enum: [muscle_gain, fat_loss, weight_loss, strength, endurance]
 *               description:
 *                 type: string
 *                 example: "Generated by Gemini AI based on my preferences"
 *     responses:
 *       201:
 *         description: Program saved successfully
 *       400:
 *         description: Validation error
 */
router.post('/workout-suggestion/save', async (req, res) => {
  try {
    const { name, days_per_week, goal, description } = req.body

    if (!name || !days_per_week || !goal) {
      return res.status(400).json({
        errors: ['name, days_per_week and goal are required to save the program']
      })
    }

    const program = await programRepository.create(req.user.userId, {
      name,
      description: description || 'Generated by Gemini AI',
      goal,
      days_per_week
    })

    res.status(201).json({
      message: 'AI suggestion saved as program successfully',
      program
    })
  } catch (err) {
    res.status(400).json({ error: err.message })
  }
})

/**
 * @swagger
 * /api/ai/nutrition-tip:
 *   post:
 *     summary: Get AI powered nutrition tip
 *     tags: [AI Suggestions]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [goal]
 *             properties:
 *               goal:
 *                 type: string
 *                 enum: [muscle_gain, fat_loss, weight_loss, strength, endurance]
 *     responses:
 *       200:
 *         description: AI nutrition tip
 *       404:
 *         description: Profile not found
 */
router.post('/nutrition-tip', async (req, res) => {
  try {
    const profile = await profileRepository.findByUserId(req.user.userId)
    if (!profile) {
      return res.status(404).json({
        error: 'Profile not found. Please create your profile first.'
      })
    }

    const goal = req.body.goal || 'strength'
    const report = calorieService.calculateFullReport(profile, goal)

    const tip = await geminiService.generateNutritionTip(
      report.target_calories,
      report.macros,
      goal,
      profile.weight_kg
    )

    res.json(tip)
  } catch (err) {
    res.status(503).json({ error: err.message })
  }
})

module.exports = router